services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    pull_policy: never
    restart: unless-stopped
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/wordpress
  
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    pull_policy: never
    restart: unless-stopped
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_root_password
      - db_password

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    pull_policy: never
    restart: unless-stopped
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/wordpress
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      WP_ADMIN_PASSWORD_FILE: /run/secrets/admin_password
      MYSQL_HOSTNAME: mariadb
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
    secrets:
      - db_password
      - admin_password

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  admin_password:
    file: ../secrets/admin_password.txt

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ltcherep/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ltcherep/data/wordpress

networks:
  inception:
    driver: bridge
